# Generated by Django 3.1.2 on 2020-12-02 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('menu', '0002_auto_20201203_0216'),
        ('product', '0001_initial'),
        ('account', '0002_auto_20201203_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('include_taxes_in_prices', models.BooleanField(default=True)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('charge_taxes_on_shipping', models.BooleanField(default=True)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('default_weight_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz'), ('g', 'g')], default='kg', max_length=10)),
                ('automatic_fulfillment_digital_products', models.BooleanField(default=False)),
                ('default_digital_max_downloads', models.IntegerField(blank=True, null=True)),
                ('default_digital_url_valid_days', models.IntegerField(blank=True, null=True)),
                ('default_mail_sender_name', models.CharField(blank=True, default='', max_length=78, validators=[django.core.validators.RegexValidator('[\\n\\r]', code='forbidden_character', inverse_match=True, message='New lines are not allowed.'), django.core.validators.MaxLengthValidator(78)])),
                ('default_mail_sender_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_set_password_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bottom_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menu')),
                ('company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('homepage_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.collection')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menu')),
            ],
            options={
                'permissions': (('manage_settings', 'Manage settings.'), ('manage_translations', 'Manage translations.')),
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site.sitesettings')),
            ],
            options={
                'unique_together': {('language_code', 'site_settings')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.sitesettings')),
            ],
            options={
                'unique_together': {('site_settings', 'name')},
            },
        ),
    ]
