# Generated by Django 3.1.2 on 2020-12-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='charge_taxes_on_shipping',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='display_gross_prices',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='include_taxes_in_prices',
        ),
    ]
