# Generated by Django 3.1.8 on 2021-07-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherTranslation',
        ),
    ]
