# Generated by Django 3.1.4 on 2020-12-23 02:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201222_1004'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
