# Generated by Django 3.1.4 on 2020-12-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201224_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firebase_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('firebase_id', 'email')},
        ),
    ]
