# Generated by Django 3.1.2 on 2020-12-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='collections',
            field=models.ManyToManyField(blank=True, to='product.Collection'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='saletranslation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='discount.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AddField(
            model_name='sale',
            name='collections',
            field=models.ManyToManyField(blank=True, to='product.Collection'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchertranslation',
            unique_together={('language_code', 'voucher')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchercustomer',
            unique_together={('voucher', 'customer_email')},
        ),
        migrations.AlterUniqueTogether(
            name='saletranslation',
            unique_together={('language_code', 'sale')},
        ),
    ]
