# Generated by Django 3.1.8 on 2021-07-16 05:35

import apps.payment
from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('order', '0002_auto_20210716_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('to_confirm', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('charge_status', models.CharField(choices=[('not-charged', 'Not charged'), ('partially-charged', 'Partially charged'), ('fully-charged', 'Fully charged'), ('partially-refunded', 'Partially refunded'), ('fully-refunded', 'Fully refunded')], default='not-charged', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_company_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_city_area', models.CharField(blank=True, max_length=128)),
                ('billing_postal_code', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('cc_first_digits', models.CharField(blank=True, default='', max_length=6)),
                ('cc_last_digits', models.CharField(blank=True, default='', max_length=4)),
                ('cc_brand', models.CharField(blank=True, default='', max_length=40)),
                ('cc_exp_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cc_exp_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='checkout.checkout')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('auth', 'Authorization'), ('refund', 'Refund'), ('capture', 'Capture'), ('void', 'Void'), ('confirm', 'Confirm')], max_length=10)),
                ('is_success', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('error', models.CharField(choices=[(apps.payment.TransactionError['INCORRECT_NUMBER'], 'incorrect_number'), (apps.payment.TransactionError['INVALID_NUMBER'], 'invalid_number'), (apps.payment.TransactionError['INCORRECT_CVV'], 'incorrect_cvv'), (apps.payment.TransactionError['INVALID_CVV'], 'invalid_cvv'), (apps.payment.TransactionError['INCORRECT_ZIP'], 'incorrect_zip'), (apps.payment.TransactionError['INCORRECT_ADDRESS'], 'incorrect_address'), (apps.payment.TransactionError['INVALID_EXPIRY_DATE'], 'invalid_expiry_date'), (apps.payment.TransactionError['EXPIRED'], 'expired'), (apps.payment.TransactionError['PROCESSING_ERROR'], 'processing_error'), (apps.payment.TransactionError['DECLINED'], 'declined')], max_length=256, null=True)),
                ('customer_id', models.CharField(max_length=256, null=True)),
                ('gateway_response', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.payment')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
